### ISSUE TITLE
do you maintain logger_flutter?

### ISSUE THREAD

**Issue by jjangga0214** [leisim/logger#112]
Readme guides readers to use logger_flutter, but the package has not been maintained.
`logger_flutter` even [requires the logger version ">=0.7.0"](https://github.com/leisim/logger_flutter/blob/1e4d87d7153b0d8d9bb2decaaf7ed89000c8f953/pubspec.yaml#L14), which is outdated. (Though there's a [PR](https://github.com/leisim/logger_flutter/pull/16) for this specific issue)

![Screenshot from 2021-10-05 22-02-12](https://user-images.githubusercontent.com/28584151/136028016-026f0b85-6a83-43db-bd52-92c6b04edbc7.png)

**Comment by haarts** [comment]
I do not maintain it and I'll remove any reference to it.

**Comment by jjangga0214** [comment]
@haarts Can I ask why you do not maintain it?

1. You are busy. => Maybe finding a maintainer?
2. You do not no longer think adding `logger_flutter` is a good practice.
3. Something other..?
