### ISSUE TITLE
Flutter 2.8.1 Stable version solving fail

### ISSUE THREAD

**Issue by peekpt** [leisim/logger#122]
`Because every version of flutter_test from sdk depends on async 2.8.2 and every version of logger_flutter from git depends on async 2.8.1, flutter_test from sdk is incompatible with logger_flutter from git.`

```
flutter upgrade

Flutter is already up to date on channel stable
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

```

**Comment by haarts** [comment]
Is this still relevant?

**Comment by peekpt** [comment]
No , closing.
