### ISSUE TITLE
Is there anyway for sharing the logs of the app to some file, like .txt?

### ISSUE THREAD

**Issue by PauloRutkoski** [leisim/logger#124]

**Comment by qoob23** [comment]
Hi! You can extend `LogOutput` class to create a file-based implementation.
Indeed there is one, but it is not exported from logger by default. You can import it manually using
```dart
import 'package:logger/src/outputs/file_output.dart';
```

**Comment by PauloRutkoski** [comment]
Ok, I'll see it. Thanks!
