### ISSUE TITLE
Add colors param to SimplePrinter

### ISSUE THREAD

**Issue by galki** [leisim/logger#13]
```
SimplePrinter(colors: true)
```

_**Reason:**_ color is easier than having to search for `[E] ...`

**Comment by haarts** [comment]
Wouldn't the `PrettyPrinter` be best suited for this purpose?

**Comment by galki** [comment]
Perhaps. The problem is that I have limited console space and `PrettyPrinter` eats up a lot of it. It would make work easier to have the option to output single-line logs which would stand out clearly from the rest of the non-log output... even if it was a single hard-coded color other than gray.

**Comment by haarts** [comment]
Yesterday I've done quite a bit of research into colouring console output. The way I'm thinking about it now is that this would be a good feature to have. I want to implement it as follows:
- detect if a terminal is attached and if that terminal supports ANSI escapes
- iff so color the output. I'm planning to use the stdlib io for this an phase out our custom coloring code

So it would be an automatic process. I hope I have time for this end of this week/beginning of next week.
