### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [leisim/logger#15]
Is there any reason to instantiate always a logger instead of do in a static way like Android logcat?

Logger.d(...)

**Comment by haarts** [comment]
I can think of several reasons. You could have several loggers for different parts of your application, each with different outputs. Or have one logger write to stdout and another (for the same log event) to a central logging service.
I was going to say that you could have different loggers for different parts of the app with different log levels but that is unsupported. All loggers share the same log level.

**Comment by haarts** [comment]
No longer do logger share the same log level (since 60bb23ffc7edd0d96dd8c8c637d23ef313e295d7).
