### ISSUE TITLE
AnsiColor.fg with normal print does not work in cmd output

### ISSUE THREAD

**Issue by ride4sun** [leisim/logger#16]
I thought to use your class AnsiColor for another purpose and tried this to see just some colored output in the command prompt but it did not do anything. 
Any idears?

 print('${AnsiColor.fg(208)} Should that lead to a colored text ?');

**Comment by haarts** [comment]
That is odd. Exactly your code snippet works for me. Does your terminal support coloured output? What terminal are you using?

**Comment by ride4sun** [comment]
The terminal inside Android Studio on Windows 10 (cmd prompt)

**Comment by haarts** [comment]
I confirm that this is an issue in Android Studio (v 3.5.2). The IntelliJ IDEA (on which Android Studio is build) does not support ANSI escape codes. After a long dig this will tell you:

```dart
import 'dart:io' as io;
print(io.stdout.supportsAnsiEscapes);
```

I believe the package should use something like this to detect support and either use or omit the ANSI escape codes.

Long story short; the snippet works on a regular terminal but not in Android Studio/IntelliJ. I also strongly suspect XCode won't work.

I hope this clarifies things. If not please feel free to re-open the issue.
