### ISSUE TITLE
It affects performance

### ISSUE THREAD

**Issue by minh98** [leisim/logger#17]
When printing a long string, the frame is dropped

**Comment by minh98** [comment]
i got `282 ms/ frame` when show long string from `https://jsonplaceholder.typicode.com/photos`

**Comment by demsey2** [comment]
the logger should only be enabled in dev, in production, you should run 
```
if (isInDebugMode) {
    Logger.level = Level.verbose;
  } else {
    Logger.level = Level.nothing;
  }
```

**Comment by minh98** [comment]
yes. thank you.
