### ISSUE TITLE
Log output to a file

### ISSUE THREAD

**Issue by maheshmnj** [leisim/logger#18]
can we have a feature to log output to a file and generate a log report

**Comment by Laban1** [comment]
Yes, the ability to log to a file would be great, so that you can debug issues in the field when no Debug console is available!

**Comment by leisim** [comment]
There is already the `FileOutput` but agree it would be a cool feature. I neglected logger recently because of my other projects. I hope to have more time soon...

**Comment by haarts** [comment]
Like so (I think):
```dart
var logger = Logger(output: FileOutput(File('some-file.txt'));
```

**Comment by maheshmnj** [comment]
I tried above I am getting this error 
```[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = 'logs.txt' (OS Error: Read-only file system, errno = 30)```

**Comment by Laban1** [comment]
@maheshmnj Try specifying the path, e.g.

    Directory directory = await getApplicationDocumentsDirectory();
    String path = join(directory.path, "some-log.txt");

**Comment by haarts** [comment]
@maheshmnj from the error message it looks like you are trying to write to a read only file system. Try logging in a different path.
