### ISSUE TITLE
Can't get the phone shake to work to work in Flutter

### ISSUE THREAD

**Issue by atreeon** [leisim/logger#20]
I have created the following flutter program with the following dependencies.
```
  logger_flutter: ^0.7.0+2
  logger: ^0.7.0+2
```
When I run it locally on an emulator the logs are displayed in my console.  I have tried to do the phone shake on the emulator but I wasn't sure if the emulator was actually doing a shake.  I then installed the app on my phone using flutter install.  It seemed to work once, I don't think the code change much if at all, but now I can't get the phone shake to work again.  Any ideas?  I have similar code on another app and it didn't work there either.

```
void main() {
  Logger.level = Level.verbose;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    Logger().i("app starting");
    return MaterialApp(
      title: 'Flutter Demo',
      home: LogConsoleOnShake(
          child: Scaffold(body: SafeArea(child: Text("logging example3")))),
    );
  }
}
```

**Comment by clicksrv** [comment]
To shake your emulator, you need to open the emulator menu, and select Virtual Sensors. Shake the phone on that screen and it should work fine.

**Comment by haarts** [comment]
Please report back if @clicksrv suggestion did not work. For now I'm closing the issue.
