### ISSUE TITLE
color not working in android studio and noise value

### ISSUE THREAD

**Issue by tbm98** [leisim/logger#3]
![Screenshot-20190706225532-1451x1023](https://user-images.githubusercontent.com/52562340/60758482-69cef500-a041-11e9-9d70-1bd0df59fdd8.png)

**Comment by tbm98** [comment]
value is exactly when i set colors is false in PrettyPrinter but color still not working :)

**Comment by howardwkim** [comment]
Appears to be a known bug #1

I set `colors` to false to remove the extra output and to stop truncation (my logs had `<...>` all over the place).
I turned on `printEmojis` for visual cues.
Still better than the stock logging solution I was using.

**Comment by leisim** [comment]
I'm currently fixing this...

**Comment by haarts** [comment]
Duplicate of #2
