### ISSUE TITLE
All the lines are discombobulated, really don't help, can we add an option to remove them?

### ISSUE THREAD

**Issue by SnowyNomad** [leisim/logger#36]
![image](https://user-images.githubusercontent.com/7461546/75822214-37f36700-5d65-11ea-907a-37f9a39026c3.png)

**Comment by pvegh** [comment]
I agree, such a distracting "feature". I want them gone!
Please add an option NOT to print the lines at all.

**Comment by SnowyNomad** [comment]
I started using LogfmtPrinter, instead of PrettyPrinter and it is clean now  I think when I first tested, something hadn't taken.
