### ISSUE TITLE
Logs not printing when running on server

### ISSUE THREAD

**Issue by LibertyBeta** [leisim/logger#37]
So... while is looks like this should work server side. it doesn't print any logs at all.

**Comment by haarts** [comment]
Which filter are you using? If it's the `ProductionFilter` it won't log anything. Try using the `DebugFilter`.

(I'm considering removing the filters since they seem more trouble than they are worth)

**Comment by LibertyBeta** [comment]
Yep, that worked. What I would suggest is not removing the filters, but changing the default and making them more clear. I would assume a debug filter to give me more logs, not less.

**Comment by haarts** [comment]
@LibertyBeta I've taken your suggestion to hard and renamed the DebugFilter to DevelopmentFilter. See #38
