### ISSUE TITLE
Readability of the error messages

### ISSUE THREAD

**Issue by synw** [leisim/logger#4]
The error messages in red and purple are hard to read. If the message could print with no color it would be much easier. This applies for error level and critical level: the others are readable. I think the error level messages are specially important and it would be nice to be able to read them quick without having to take a closer look at the red text.

Compare this:

![err1](https://user-images.githubusercontent.com/12034394/60784546-e1cf1500-a13e-11e9-90a3-8739dce51713.png)

To that:

![err2](https://user-images.githubusercontent.com/12034394/60784558-ed224080-a13e-11e9-883f-862939242b84.png)

In `printer/pretty_printer.dart` line 221 could be changed from

```dart
println(color('$verticalLine $emoji$line'));
```

To:      

```dart
println("${color('$verticalLine $emoji')}$line");
```

Or maybe using an option? Actually it is not possible to extend the class to override `formatAndPrint` due to many internal stuff used in it.

As well making the call stack function list more readable in error and critical levels would be good too. The colors are very useful to instantly know the log level of the message and I want to keep them while being able to read quickly the error messages.

**Comment by leisim** [comment]
Thanks, I'm currently working on that. In the next version you can customize the colors and logging format...

**Comment by synw** [comment]
Ok I"ll check it out when it will be out
