### ISSUE TITLE
Colors not showing on VS Code debug console

### ISSUE THREAD

**Issue by miguelpruivo** [leisim/logger#43]
Hi, I'm not quite sure if this is an issue with the package itself or some VS Code update, but lately, colors have not being present on debug console. Do you have an idea why?

Thank you.

**Comment by haarts** [comment]
There were colours previously? That's odd. VS Code never displayed any colours because that term is not able to handle ANSI escape codes.

**Comment by miguelpruivo** [comment]
Yes. Mine had colors for a while. Something have changed it.

**Comment by haarts** [comment]
Have a look at the solution in #2.
At some point I really want to make this work in the various IDEs but I have no easy solution.
