### ISSUE TITLE
PrefixPrinter and HybridPrinter missing

### ISSUE THREAD

**Issue by kiesman99** [leisim/logger#56]
Hey there :) I don't know if i missed somthing but unfortunately the PrefixPrinter and the HybridPrinter are note available if you download logger Version 0.9.1. Too bad, because I really like the logger 😄 

![image](https://user-images.githubusercontent.com/17956096/88368124-b04adb00-cd8d-11ea-8e57-699aae758c96.png)

**Failing**: PrefixPrinter and HybridPrinter are not available
**Steps to reproduce**: Add following to your pubspec. yaml: logger: ^0.9.1
**What should happen?**: The PrefixPrinter and HybridPrinter should be available for usage.

Thank you very much!

**Comment by haarts** [comment]
I'll get on it once I get back from my holiday. I don't think these loggers
are released yet.

**Comment by haarts** [comment]
I've just release version 0.9.2 which includes these printers!

**Comment by kiesman99** [comment]
@haarts Thank you very much!
