### ISSUE TITLE
Every Line ends with a "[0m"

### ISSUE THREAD

**Issue by srinivas-codezyng** [leisim/logger#58]
Hi, I started using logger in my project. In Android studio, In every line there is "[0m" appended.
Please let me know if I am doing something wrong with the usage.

<img width="1119" alt="Screenshot 2020-07-30 at 8 43 58 PM" src="https://user-images.githubusercontent.com/56709842/88941165-532bb980-d2a6-11ea-8719-0cd0d99a01dc.png">

**Comment by haarts** [comment]
That's because AndroidStudio is unable to display colors. Set the constructor argument `colors` to `false` for the [`PretterPrinter`](https://pub.dev/documentation/logger/latest/logger/PrettyPrinter-class.html). Like so `Logger(printer: PrettyPrinter(colors: false))`.
