### ISSUE TITLE
Nothing printed to console with logger 0.9.3

### ISSUE THREAD

**Issue by shimaatech** [leisim/logger#63]
Nothing is printed to the console with logger 0.9.3.
it works with 0.9.2

**Comment by ash2osh** [comment]
same problem here

**Comment by haarts** [comment]
I'll look into it first thing Monday.

**Comment by gksrb4** [comment]
> same problem here

1++
Exception has occurred.
FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))

**Comment by phuongphally** [comment]
same problem here

**Comment by dev-juyoung** [comment]
same problem here

**Comment by haarts** [comment]
What exactly are you using? Just a plain `Logger().e('some message')`?

**Comment by haarts** [comment]
The issue is fixed in master by reverting the offending commit. I'm releasing soon.

**Comment by haarts** [comment]
> > same problem here
> 
> 1++
> 
> ```
> Exception has occurred.
> FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))
> ```

Is is a different issue I think. I'm guessing you're using the MultiOutput?

**Comment by gksrb4** [comment]
> > > same problem here
> > 
> > 
> > 1++
> > ```
> > Exception has occurred.
> > FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))
> > ```
> 
> Is is a different issue I think. I'm guessing you're using the MultiOutput?

what is multiouput?

It worked well before upgrade module. 
so, I currently downgrade 0.9.2 and then It works well.
