### ISSUE TITLE
A problem occurred configuring project ':logger_flutter'.

### ISSUE THREAD

**Issue by certhon** [leisim/logger#8]
FAILURE: Build failed with an exception.

* Where:
Script '/Users/chenhong/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 221

* What went wrong:
A problem occurred configuring project ':logger_flutter'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':logger_flutter' of type org.gradle.api.Project.
   > Could not find method debugProvided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by leisim** [comment]
Thanks for reporting, this has been fixed in logger_flutter v0.7.1
