### ISSUE TITLE
dart fmt

### ISSUE THREAD

**Issue by IanWorthington** [leisim/logger#86]
Anyone know what formatter this project needs?  I'm using the dartfmt built into Android Studio 412 and the checker is rejecting it.

**Comment by haarts** [comment]
Android Studio is not actually using dartfmt but something home brew. You can configure Android Studio (and IntelliJ et al) to use `dart fmt`.

**Comment by IanWorthington** [comment]
Hmm.

Well, I chased down in settings where this is stored and it says:

> "Code is formatted using the dartfmt tool from the Dart SDK."
