### ISSUE TITLE
Colours not working after upgrading to Flutter 2.0

### ISSUE THREAD

**Issue by MingSern** [leisim/logger#91]
After upgrading to Flutter 2.0, colour text not working anymore, version 1.22.6 still working fine.
Below shows the output after upgrading to Flutter 2.0

![image](https://user-images.githubusercontent.com/40648559/111940555-05501400-8b0a-11eb-92ff-e3bf36e4c3c5.png)

**Comment by iDevOrz** [comment]
You may want to take a look at #2
